### Dataset `Otomotif Mobil`

Dataset ini merupakan data bawaan dari _package_ `datasets` pada aplikasi R. Data ini memiliki beberapa peubah, yaitu:
1. **mpg** (miles/(us) gallon), yakni jarak tempuh suatu mobil dibandingkan dengan konsumsi 1 galon bahan bakar.
2. **cyl** (number of cylinders), yakni banyaknya silinder pada mesin mobil.
3. **disp** (displacement), yakni volume mesin sebagai alat ukur tenaga yang dihasilkan.
4. **hp** (horsepower), yakni tenaga mesin yang dihasilkan dalam satuan horsepower.
5. **drat** (rear axle ratio), yakni rasio torsi mesin penggerak depan.
6. **wt** (weight), yakni berat mobil.
7. **qsec** (1/4 mile time), yakni kemampuan akselerasi mobil.
8. **vs** (engine type), yakni jenis mesin mobil (0=V-shaped, 1=Straight).
9. **am** (transmission type), yakni jenis transmisi mobil (0=otomatis, 1=manual).
10. **gear** (number og forward gears), yakni banyaknya gear depan mobil.

Sebagai catatan bahwa peubah respon pada analisis regresi adalah peubah yang menggunakan skala data kontinu seperti: **mpg**, **cyl**, **disp**, **drat**, **wt**, **qsec**, atau **gear**. Sedangkan peubah penjelas dapat berupa skala data kategorik maupun kontinu.

### Dataset `Karakteristik Batu`

Dataset ini merupakan data bawaan dari _package_ `datasets` pada aplikasi R. Data ini memiliki beberapa peubah, yaitu:
1. **area** (pixel), yakni luasan area berpori.
2. **per** (perimeter in pixel), yakni ukuran perimeter.
3. **shape** (perimeter/sqrt), yakni ukuran  perimeter per satu kaki luas area.
4. **perm** (permeability), yakni permeabilitas dalam mili-Darcies.

Sebagai catatan bahwa peubah respon pada analisis regresi adalah peubah yang menggunakan skala data kontinu (semua peubah pada dataset `Karakteristik Batu` dapat digunakan sebagai peubah respon).

### Dataset `Temperatur dan Tekanan`

Dataset ini merupakan data bawaan dari _package_ `datasets` pada aplikasi R. Data ini memiliki beberapa peubah, yaitu:
1. **temperature** (derajat Fahrenheit), yakni suhu.
2. **pressure** (pascal), yakni tekanan yang dihasilkan.

Sebagai catatan bahwa peubah respon pada analisis regresi adalah peubah yang menggunakan skala data kontinu (semua peubah pada dataset `Temperatur dan Tekanan` dapat digunakan sebagai peubah respon).